# 7.- Arreglos con NUMPY

En este capítulo aprenderás a utilizar algunas cualidades básicas de NumPy (Numerical Python).
NumPy es una de las librerías más populares de Python, ya que puede procesar listas de múltiples
dimensiones

## 7.2.- Arreglo de Datos

Como en la sección anterior, invocaremos a la librería NumPy como np

In [14]:
import numpy as np

Armemos un arreglo de todos los factoriales del 1 al 6

In [2]:
factoriales = np.array([1,2,6,24,120,720])

Verifica el tipo de objeto que generamos

In [27]:

type(factoriales)
factoriales
np.array([ 1, 2, 6, 24, 120, 720])

array([  1,   2,   6,  24, 120, 720])

La función array copia automáticamente las dimensiones del argumento. Por ejemplo, el siguiente arreglo (array) está formado por tres filas y dos columnas.

In [26]:
np.array([[3,4],[6,7],[10,11]])
np.array([[ 3, 4],
       [ 6, 7],
       [10, 11]])

array([[ 3,  4],
       [ 6,  7],
       [10, 11]])

#### Por tu cuenta

Arma un arreglo de una dimensión desde una compresnidón de lista que produce todos los números nones del 1 al 30

In [25]:
import numpy as np
enteros = np.array([[9,10,11,12],[8,7,6,5]])
enteros
np.array([[ 9, 10, 11, 12],
[ 8, 7, 6, 5]])
flotantes=np.array([[9**(1/2),10**(1/2),3.33,],[10/3,3.4,3.03]])
flotantes
np.array([[3. , 3.16227766, 3.33 ],
[3.33333333, 3.4 , 3.03 ]])

array([[3.        , 3.16227766, 3.33      ],
       [3.33333333, 3.4       , 3.03      ]])

### 7.2.2 - Atributos de Arreglos

En esta sección usaremos los siguientes 2 arreglos

enteros = np.array([[9,10,11,12],[8,7,6,5]])

flotantes=np.array([[9**(1/2),10**(1/2),3.33,],[10/3,3.4,3.03]])

In [ ]:
import numpy as np
enteros = np.array([[9,10,11,12],[8,7,6,5]])
enteros
array([[ 9, 10, 11, 12],
[ 8, 7, 6, 5]])
flotantes=np.array([[9**(1/2),10**(1/2),3.33,],[10/3,3.4,3.03]])
flotantes
array([[3. , 3.16227766, 3.33 ],
[3.33333333, 3.4 , 3.03 ]])

Checa el tipo de elemento con dtype

In [28]:
enteros.dtype
np.dtype('int32') # en algunas plataformas puede ser int64
flotantes.dtype
np.dtype('float64')

dtype('float64')

Revisa que puedes ver dimensione con ndim y forma con shape del arreglo

In [19]:
enteros.ndim

2

In [22]:

enteros.shape


(2, 4)

Size y itemsize te permite conocer el numero de elemntos y de bytes para almacenar

In [30]:
enteros.size

enteros.itemsize



8

Se puede iterar facilmente a través de un arreglo

In [31]:
flotantes.size

flotantes.itemsize


8

#### Por tu cuenta

Para el arreglo que armaste en el "Por tu cuenta" previo, checa el numero de dmiensiones y forma del arreglo

In [32]:
for fila in flotantes:
    for columna in fila:
            print(columna, end=' ')
print()

3.0 3.1622776601683795 3.33 3.3333333333333335 3.4 3.03 


### 7.2.3 - Creando Arreglos desde Rangos

La función arange (una sola R!!!!) nos permite crear rangos de enteros. Crea:

- Un arreglo del 0 al 7
- Un arreglo del 3 al 7
- Un arreglo del 12 al 2 en pasos de 3 en 3 (si, en orden inverso)

In [33]:
arr1 = np.arange(0, 8)
print(arr1) 

[0 1 2 3 4 5 6 7]


In [34]:
arr2 = np.arange(3, 8)
print(arr2)

[3 4 5 6 7]


In [35]:
arr3 = np.arange(12, 1, -3)
print(arr3)

[12  9  6  3]


Tambien se pueden usar tamaños de paso no enteros. Crea un arreglo con linspace de 0 al 1 que vaya de .25 en .25

In [36]:
arr = np.linspace(0, 1, num=5)  
print(arr)

[0.   0.25 0.5  0.75 1.  ]


Y se puede cambiar la forma del arreglo con reshape. Crea un arreglo con arange que vaya del 21 al 1 en orden inverso, y luego dale forma de matriz de 4x5

In [41]:

arr = np.arange(21, 0, -1)
print("Arreglo original:")
print(arr)


matriz = arr.reshape(4, 5)
print("\nMatriz 4x5:")
print(matriz)


Arreglo original:
[21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


ValueError: cannot reshape array of size 21 into shape (4,5)

Checate que si el arreglo tiene 1000 o más elementos, numpy no muestra la totalidad de los datos. Generaun arreglo de 0 a 9999 y dale forma de 5 x 2000

In [42]:
import numpy as np

arr = np.arange(10000)

matriz = arr.reshape(5, 2000)

print(matriz)


[[   0    1    2 ... 1997 1998 1999]
 [2000 2001 2002 ... 3997 3998 3999]
 [4000 4001 4002 ... 5997 5998 5999]
 [6000 6001 6002 ... 7997 7998 7999]
 [8000 8001 8002 ... 9997 9998 9999]]


#### Por tu cuenta

Usa la función arange para crear una rreglo de 20 enteros pares del 42 al 80, y luego rearmalo en una matriz de 4x5

In [43]:
import numpy as np


arr = np.arange(42, 82, 2)  

matriz = arr.reshape(4, 5)

print(matriz)


[[42 44 46 48 50]
 [52 54 56 58 60]
 [62 64 66 68 70]
 [72 74 76 78 80]]


### 7.2.4 - ¿Que tan más rapido es un arreglo?

Usa la magia %timeit y la librería random para crear una comprensión de lista que simule un tiro de dao 6000000 de veces y medir su tiempo

In [47]:
import random
import time


inicio = time.time()


dados = [random.randint(1, 6) for _ in range(6_000_000)]


fin = time.time()

print(f"Tiempo de ejecución: {fin - inicio:.4f} segundos")





Tiempo de ejecución: 5.4191 segundos


Ahora usa %timeit para medir el tiempo de un tiro de dado 6000000 de veces pero hecho con arreglo

In [48]:
import numpy as np

%timeit np.random.randint(1, 7, size=6_000_000)


143 ms ± 7.46 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### Por tu cuenta

Usa %timeit para ver que es mas rapido - una lista que sume todos los enteros del 0 al 9 999 999 o un arreglo que haga lo mismo con el metodo sum

In [49]:

%timeit sum([i for i in range(10_000_000)])

%timeit np.sum(np.arange(10_000_000))


862 ms ± 140 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
47.2 ms ± 9.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 7.3.- Operaciones con Arreglos

Arma un arreglo de todos los pares del 2 al 15.

- Sumale 1 al arreglo
- Multiplicalo por 3
- Sacale raiz cuadrada

In [50]:
pares = np.arange(2,15,2)

pares

array([ 2,  4,  6,  8, 10, 12, 14])

In [51]:
pares+1

array([ 3,  5,  7,  9, 11, 13, 15])

In [52]:
pares*3

array([ 6, 12, 18, 24, 30, 36, 42])

In [53]:
pares**(1/2)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739])

Al mismo arreglo, aplicale un +=10

In [58]:
pares +=10
pares


array([30, 32, 34, 36, 38, 40, 42])

Arma un arreglo (lista1) que vaya del 2 al 18 de 3 en 3, y otro arreglo (lista2) usando linspace que vaya del -2 al 20 dividido en 6 numeros

- Resta lista1 de lista2
- divide lista2 entre lista1

In [59]:
lista1 = np.arange(2,18,3)
lista1

array([ 2,  5,  8, 11, 14, 17])

In [60]:
lista2 = np.linspace(-2,20,6)
lista2

array([-2. ,  2.4,  6.8, 11.2, 15.6, 20. ])

In [61]:
lista2-lista1

array([-4. , -2.6, -1.2,  0.2,  1.6,  3. ])

In [62]:
lista2/lista1

array([-1.        ,  0.48      ,  0.85      ,  1.01818182,  1.11428571,
        1.17647059])

También puedes comparar los arreglos

In [63]:
lista1<lista2

array([False, False, False,  True,  True,  True])

#### Por tu cuenta

Crea un arreglo de los valores que vayan del 1 al 5, y luego elvealo al cuadrado usando **

In [64]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])


arr_cuadrado = arr ** 2

print(arr_cuadrado)


[ 1  4  9 16 25]


### 7.3.2.- Métodos de Cálculo

Considera el siguiente arreglo 

ventas=np.array( [[554,606,710,851],[1244,898,416,1763],
 [841,655,1105,1067]])


In [65]:
ventas=np.array( [[554,606,710,851],[1244,898,416,1763],
[841,655,1105,1067]])

Podemos usar métodos para calcular la sum, min, max, mean, std, var. 

In [66]:
ventas
np.array([[ 554, 606, 710, 851],
[1244, 898, 416, 1763],
[ 841, 655, 1105, 1067]])

array([[ 554,  606,  710,  851],
       [1244,  898,  416, 1763],
       [ 841,  655, 1105, 1067]])

In [67]:
ventas.sum()

np.int64(10710)

In [68]:
ventas.min()

np.int64(416)

In [69]:
ventas.max()

np.int64(1763)

In [70]:
ventas.mean()

np.float64(892.5)

In [71]:
ventas.std()

np.float64(350.56656524355924)

También es posible hacerlo por filas y columnas. Checa como se hace con axis = 1 y 0

In [72]:
ventas.var()

np.float64(122896.91666666667)

In [73]:
ventas.mean(axis=0)

array([ 879.66666667,  719.66666667,  743.66666667, 1227.        ])

In [74]:
ventas.mean(axis=1)

array([ 680.25, 1080.25,  917.  ])

#### Por tu cuenta

Usa el generador de numeros aleatoreos de numpy (np.random.randint) para crear una rreglo de 12 calificaciones aleatorias del 60 al 100, y luego dale forma en una matriz de 3x4. Calcula el promedio de todas las calificaciones, el promedio de cada columna y de cada fila. 

In [75]:
calificaciones = np.random.randint(60, 101, size=12)

In [76]:
matriz = calificaciones.reshape(3, 4)

In [77]:
promedio_total = np.mean(matriz)

In [78]:
promedio_filas = np.mean(matriz, axis=1)

In [79]:
promedio_columnas = np.mean(matriz, axis=0)

In [80]:
print("Matriz de calificaciones:")
print(matriz)
print("\nPromedio total de todas las calificaciones:", promedio_total)
print("Promedio de cada fila:", promedio_filas)
print("Promedio de cada columna:", promedio_columnas)

Matriz de calificaciones:
[[ 80 100  85  97]
 [ 70  80  77  75]
 [ 95  66  64  84]]

Promedio total de todas las calificaciones: 81.08333333333333
Promedio de cada fila: [90.5  75.5  77.25]
Promedio de cada columna: [81.66666667 82.         75.33333333 85.33333333]


## 7.4.- Indexando y Cortando arreglos

Crea el arreglo

ventas=np.array ([[ 554, 606, 710, 851],
 [1244, 898, 416, 1763],
 [ 841, 655, 1105, 1067]])
 
 - Selecciona el item 2,1
 - Selecciona el item 1,3
 - Selecciona la fila 1

In [81]:
ventas=np.array ([[ 554, 606, 710, 851],
[1244, 898, 416, 1763],
[ 841, 655, 1105, 1067]])

In [83]:
ventas[1,3]

np.int64(1763)

In [84]:
ventas[2,1]

np.int64(655)

Solicita las filas con índices 0 y 1

In [85]:
ventas[0:2]

array([[ 554,  606,  710,  851],
       [1244,  898,  416, 1763]])

Ahora para solicitar las filas con indices 1 y 2

In [86]:
ventas[1:3]

array([[1244,  898,  416, 1763],
       [ 841,  655, 1105, 1067]])

Quieres solo los elementos de la primera columna?

In [87]:
ventas[:,0]

array([ 554, 1244,  841])

Que la las columnas con indices 0 y 2?

In [88]:
ventas[:,[0,2]]

array([[ 554,  710],
       [1244,  416],
       [ 841, 1105]])

#### Por tu cuenta

Dado el siguiente arreglo

array([[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15]])

- Selecciona la segunda fila
- Selecciona la primera y tercera fila
- Selecciona las tres columnas de enmedio

In [90]:
np.array([[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [91]:
segunda_fila = arr[1]

In [92]:
primer_y_tercer_fila = arr[[0, 2]]

In [99]:
print("Segunda fila:", segunda_fila)
print("Primera y tercera fila:", primer_y_tercer_fila)


Segunda fila: 2
Primera y tercera fila: [1 3]


### 7.4.2.- Transponer

Con **reshape** puedes producir una copia superficial del arreglo con una nueva dimension. 

ventas = np.array([[ 500, 600, 550, 800],
 [1200, 800, 400,1000]])

Usa el arreglo anterior para darle dimension de 1x8

In [100]:
ventas = np.array([[ 500, 600, 550, 800],
[1200, 800, 400,1000]])

In [101]:
ventas.reshape(1,8)

array([[ 500,  600,  550,  800, 1200,  800,  400, 1000]])

In [102]:
ventas

array([[ 500,  600,  550,  800],
       [1200,  800,  400, 1000]])

El metodo **resize** modifica la forma del original (no crea copia)

In [103]:
ventas.resize(1,8)

In [104]:
ventas

array([[ 500,  600,  550,  800, 1200,  800,  400, 1000]])

Y **transpose** rapidamente le da la vuelta a filas y columnas, este se hace aplicando el atributo T, que no modifica el original, solo una vista.

In [105]:
vector_ventas=ventas.flatten()

## 7.5.- Pandas - Series

Vamos a usar estos datos para Series - tiempo_web = pd.Series([160,256,98,108])

Este es el tiempo que invierten en videojuegos 4 estudiantes

In [106]:
import pandas as pd

In [108]:
tiempo_web = pd.Series([160,256,98,108])

In [109]:
tiempo_web

0    160
1    256
2     98
3    108
dtype: int64

Para crear una serie con el mismo elemento

In [110]:
pd.Series(3.1416,range(5))

0    3.1416
1    3.1416
2    3.1416
3    3.1416
4    3.1416
dtype: float64

Acceder a un elemento es facil

In [111]:
tiempo_web[1]

np.int64(256)

Series tiene acceso a los mismos metodos que arreglos para estadistica descriptiva

In [112]:
tiempo_web.count()

np.int64(4)

In [113]:
tiempo_web.mean()

np.float64(155.5)

In [114]:
tiempo_web.min()

np.int64(98)

In [115]:
tiempo_web.max()

np.int64(256)

In [116]:
tiempo_web.std()

np.float64(72.30260484012085)

Tambien, todo esto se puede resumir con **describe**

In [117]:
tiempo_web.describe()

count      4.000000
mean     155.500000
std       72.302605
min       98.000000
25%      105.500000
50%      134.000000
75%      184.000000
max      256.000000
dtype: float64

También podemos personalizar los indices de series a traves de index

['Laura','Daniel','Alberto','Eva'] 

Asigna esos nombres

In [118]:
tiempo_web=pd.Series([160,256,98,108],index=
['Laura','Daniel','Alberto','Eva'])

In [119]:
tiempo_web

Laura      160
Daniel     256
Alberto     98
Eva        108
dtype: int64

O puedes usar un diccionario para eso:

In [120]:
tiempo_web=pd.Series({'Laura':160,'Daniel':256,
'Alberto':98,'Eva':108})

In [121]:
tiempo_web

Laura      160
Daniel     256
Alberto     98
Eva        108
dtype: int64

Puedes llamar a los elementos personalizados

In [122]:
tiempo_web['Eva']

np.int64(108)

Tambien se pueden llamar como atributos

In [123]:
tiempo_web.Alberto

np.int64(98)

#### Por tu cuenta

Usa el generador aleatorio de NumPy (np.random.randint) para generar 6 calificaciones del 60 al 100 y guardarlos en una serie. 

A continuación arma las siguientes tareas:

- Convierte el arreglo en una serie llamada calificacion
- Determina la min, max y promedio
- Produce TODAS las estadisticas descriptivas

In [124]:
calificaciones = np.random.randint(60, 101, size=6)

In [125]:
calificacion = pd.Series(calificaciones)

In [127]:
min_calificacion = calificacion.min()

In [128]:
max_calificacion = calificacion.max()


In [129]:
promedio_calificacion = calificacion.mean()

In [126]:
estadisticas = calificacion.describe()

In [130]:
print("Calificaciones:", calificacion)
print("Mínima:", min_calificacion)
print("Máxima:", max_calificacion)
print("Promedio:", promedio_calificacion)
print("\nEstadísticas Descriptivas:")
print(estadisticas)

Calificaciones: 0    92
1    90
2    98
3    89
4    98
5    63
dtype: int32
Mínima: 63
Máxima: 98
Promedio: 88.33333333333333

Estadísticas Descriptivas:
count     6.000000
mean     88.333333
std      13.002564
min      63.000000
25%      89.250000
50%      91.000000
75%      96.500000
max      98.000000
dtype: float64


## 7.6.- Pandas - DataFrames

##### Crear un Dataframe de un diccionario

Agarra este diccionario y conviertelo en un dataframe

 reg_peso = {'Vanesa':[68,67,66,65],'Kevin':[89,89,90,88],
 'Fernanda':[59,60,60,62],'Patricia':[70,68,67,65]}

In [131]:
reg_peso = {'Vanesa':[68,67,66,65],'Kevin':[89,89,90,88],
'Fernanda':[59,60,60,62],'Patricia':[70,68,67,65]}

In [132]:
peso = pd.DataFrame(reg_peso)

In [133]:
peso

Vanesa  Kevin  Fernanda  Patricia
0      68     89        59        70
1      67     89        60        68
2      66     90        60        67
3      65     88        62        65

##### El atributo Index

Añade los siguientes indices personalizados

peso.index = ['Mes 1','Mes 2','Mes 3','Mes 4']

In [134]:
peso.index = ['Mes 1','Mes 2','Mes 3','Mes 4']

In [135]:
peso

Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 2      67     89        60        68
Mes 3      66     90        60        67
Mes 4      65     88        62        65

##### Accesar Columnas

Selecciona la información de Fernanda

In [136]:
peso['Fernanda']

Mes 1    59
Mes 2    60
Mes 3    60
Mes 4    62
Name: Fernanda, dtype: int64

Selecciona la de Patricia pero como atributo

In [137]:
peso.Patricia

Mes 1    70
Mes 2    68
Mes 3    67
Mes 4    65
Name: Patricia, dtype: int64

##### Loc y iloc

Selecciona la información del Mes1 usando Loc

In [138]:
peso.loc['Mes 1']

Vanesa      68
Kevin       89
Fernanda    59
Patricia    70
Name: Mes 1, dtype: int64

Ahora solo la fila 1 usando iloc

In [139]:
peso.iloc[1]

Vanesa      67
Kevin       89
Fernanda    60
Patricia    68
Name: Mes 2, dtype: int64

Ahora del Mes 1 al Mes 3 usando loc

In [140]:
peso.loc['Mes 1':'Mes 3']

Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 2      67     89        60        68
Mes 3      66     90        60        67

Saca filas especificas (mes 1 y 3) usando loc

In [141]:
peso.loc['Mes 1':'Mes 3']

Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 2      67     89        60        68
Mes 3      66     90        60        67

Y ahora los Meses 2 y 3 de Vanesa y Patricia solamente con loc

In [142]:
peso.loc['Mes 2':'Mes 3',['Vanesa','Patricia']]

Vanesa  Patricia
Mes 2      67        68
Mes 3      66        67

##### Indices Booleanos

Dime los pesos mayores a 70kg en la tabla

In [143]:
peso[peso>=70]

Vanesa  Kevin  Fernanda  Patricia
Mes 1     NaN     89       NaN      70.0
Mes 2     NaN     89       NaN       NaN
Mes 3     NaN     90       NaN       NaN
Mes 4     NaN     88       NaN       NaN

Y ahora los pesos mayores a 65kg y menores a 80kg

In [144]:
peso[(peso>65)&(peso<80)]

Vanesa  Kevin  Fernanda  Patricia
Mes 1    68.0    NaN       NaN      70.0
Mes 2    67.0    NaN       NaN      68.0
Mes 3    66.0    NaN       NaN      67.0
Mes 4     NaN    NaN       NaN       NaN

##### Accesar una celda especifica de un Dataframe

Que pasa si solo queremos cuanto pesaba Patricia en el mes 3? Usa at

In [145]:
peso.at['Mes 3','Patricia']

np.int64(67)

Resulta que Kevin en realidad pesaba 85kg en el mes 4, cambia su valor usando at

In [146]:
peso.at['Mes 4','Kevin']=85

In [147]:
peso.at['Mes 4','Kevin']

np.int64(85)

##### Estádistica descriptiva

Puedes usar el metodo **Describe** para sacar todas las estadisticas del dataframe

In [148]:
peso.describe()

Vanesa      Kevin   Fernanda   Patricia
count   4.000000   4.000000   4.000000   4.000000
mean   66.500000  88.250000  60.250000  67.500000
std     1.290994   2.217356   1.258306   2.081666
min    65.000000  85.000000  59.000000  65.000000
25%    65.750000  88.000000  59.750000  66.500000
50%    66.500000  89.000000  60.000000  67.500000
75%    67.250000  89.250000  60.500000  68.500000
max    68.000000  90.000000  62.000000  70.000000

También puedes cambiar la cantidad de decimales usando **Precision**

In [149]:
pd.set_option('precision',1)

OptionError: Pattern matched multiple keys

In [150]:
peso.describe()

Vanesa      Kevin   Fernanda   Patricia
count   4.000000   4.000000   4.000000   4.000000
mean   66.500000  88.250000  60.250000  67.500000
std     1.290994   2.217356   1.258306   2.081666
min    65.000000  85.000000  59.000000  65.000000
25%    65.750000  88.000000  59.750000  66.500000
50%    66.500000  89.000000  60.000000  67.500000
75%    67.250000  89.250000  60.500000  68.500000
max    68.000000  90.000000  62.000000  70.000000

Y también se pueden aplicar los metodos de estadistica descriptiva individuales como mean

In [151]:
peso.mean()

Vanesa      66.50
Kevin       88.25
Fernanda    60.25
Patricia    67.50
dtype: float64

##### Transponer

Si quisieramos voltear el dataframe, tendríamos que hacer el método T

In [152]:
peso.T

Mes 1  Mes 2  Mes 3  Mes 4
Vanesa       68     67     66     65
Kevin        89     89     90     85
Fernanda     59     60     60     62
Patricia     70     68     67     65

Y ahora eso nos ayudaría a sacar los estadísticos para los meses en vez de para las personas

In [154]:
peso.T.describe()

Mes 1      Mes 2      Mes 3     Mes 4
count   4.00000   4.000000   4.000000   4.00000
mean   71.50000  71.000000  70.750000  69.25000
std    12.60952  12.516656  13.200379  10.59481
min    59.00000  60.000000  60.000000  62.00000
25%    65.75000  65.250000  64.500000  64.25000
50%    69.00000  67.500000  66.500000  65.00000
75%    74.75000  73.250000  72.750000  70.00000
max    89.00000  89.000000  90.000000  85.00000

Y el peso promedio por mes de nuestra gente

In [153]:
peso.T.mean()

Mes 1    71.50
Mes 2    71.00
Mes 3    70.75
Mes 4    69.25
dtype: float64

##### Ordenar el Dataframe

Ahora vamos a arreglar el dataframe por fila, con los indices en orden descendente

In [155]:
peso.sort_index(ascending=False)

Vanesa  Kevin  Fernanda  Patricia
Mes 4      65     85        62        65
Mes 3      66     90        60        67
Mes 2      67     89        60        68
Mes 1      68     89        59        70

Las columnas en orden ascendente

In [156]:
peso.sort_index(axis=1)

Fernanda  Kevin  Patricia  Vanesa
Mes 1        59     89        70      68
Mes 2        60     89        68      67
Mes 3        60     90        67      66
Mes 4        62     85        65      65

Y también se vale ordenar los valores según una fila o columna especifica.  El siguiente código ordena de forma descendente los datos del DataFrame con respecto
a los valores del Mes 1.

In [157]:
peso.sort_values(by='Mes 1', axis=1,ascending=False)

Kevin  Patricia  Vanesa  Fernanda
Mes 1     89        70      68        59
Mes 2     89        68      67        60
Mes 3     90        67      66        60
Mes 4     85        65      65        62